/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "快速开始",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-090a51f8",
      "path": "/"
    },
    {
      "title": "Card",
      "frontmatter": {},
      "regularPath": "/componentDocs/DemoCard.html",
      "relativePath": "componentDocs/DemoCard.md",
      "key": "v-7d39256e",
      "path": "/componentDocs/DemoCard.html",
      "headers": [
        {
          "level": 3,
          "title": "示例",
          "slug": "示例"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": [
      "/",
      "/componentDocs/DemoCard"
    ]
  }
}